<?php

namespace ContainerXwX41kA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z6kC591Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z6kC591' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z6kC591'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'faits' => ['privates', 'App\\Repository\\FaitRepository', 'getFaitRepositoryService', true],
            'mois' => ['privates', 'App\\Repository\\MoisRepository', 'getMoisRepositoryService', true],
            'users' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'faits' => 'App\\Repository\\FaitRepository',
            'mois' => 'App\\Repository\\MoisRepository',
            'users' => 'App\\Repository\\UserRepository',
        ]);
    }
}
