<?php

namespace ContainerFBDLbon;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ojk124qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ojk124q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ojk124q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'faitsRepository' => ['privates', 'App\\Repository\\FaitRepository', 'getFaitRepositoryService', true],
            'mois' => ['privates', 'App\\Repository\\MoisRepository', 'getMoisRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'users' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'faitsRepository' => 'App\\Repository\\FaitRepository',
            'mois' => 'App\\Repository\\MoisRepository',
            'paginator' => '?',
            'users' => 'App\\Repository\\UserRepository',
        ]);
    }
}
