<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFI2O0Ly\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFI2O0Ly/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFI2O0Ly.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFI2O0Ly\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFI2O0Ly\App_KernelProdContainer([
    'container.build_hash' => 'FI2O0Ly',
    'container.build_id' => '0c989389',
    'container.build_time' => 1650295924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFI2O0Ly');
