<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRLx1TZR\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRLx1TZR/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRLx1TZR.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRLx1TZR\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRLx1TZR\App_KernelProdContainer([
    'container.build_hash' => 'RLx1TZR',
    'container.build_id' => '07ef4870',
    'container.build_time' => 1650294920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRLx1TZR');
