<?php

namespace ContainerFnKGSAC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9dX6zbmService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9dX6zbm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9dX6zbm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'faits' => ['privates', 'App\\Repository\\FaitRepository', 'getFaitRepositoryService', true],
            'users' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'faits' => 'App\\Repository\\FaitRepository',
            'users' => 'App\\Repository\\UserRepository',
        ]);
    }
}
