<?php

namespace ContainerFnKGSAC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_JRrIWGService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.JRrIWG_' shared service.
     *
     * @return \Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AdminController::changePassword()": the $encoder argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface".');
    }
}
