<?php

namespace ContainerFnKGSAC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCanalRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CanalRepository' shared autowired service.
     *
     * @return \App\Repository\CanalRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CanalRepository'] = new \App\Repository\CanalRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
