<?php

namespace ContainerFI2O0Ly;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::changePassword' => ['privates', '.service_locator.EfscBmv', 'get_ServiceLocator_EfscBmvService', true],
            'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController::edit' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController::usersList' => ['privates', '.service_locator.Nhkyqt4', 'get_ServiceLocator_Nhkyqt4Service', true],
            'App\\Controller\\FaitController::deleteBudget' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FaitController::editBudget' => ['privates', '.service_locator.Z6kC591', 'get_ServiceLocator_Z6kC591Service', true],
            'App\\Controller\\FaitController::newBudget' => ['privates', '.service_locator.Z6kC591', 'get_ServiceLocator_Z6kC591Service', true],
            'App\\Controller\\FaitController::reporting' => ['privates', '.service_locator.9dX6zbm', 'get_ServiceLocator_9dX6zbmService', true],
            'App\\Controller\\FaitController::saisieBudgetaire' => ['privates', '.service_locator.Ojk124q', 'get_ServiceLocator_Ojk124qService', true],
            'App\\Controller\\MoisController::choixMois' => ['privates', '.service_locator.Bs1IPwp', 'get_ServiceLocator_Bs1IPwpService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.Kn9Vk3z', 'get_ServiceLocator_Kn9Vk3zService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\AdminController:changePassword' => ['privates', '.service_locator.EfscBmv', 'get_ServiceLocator_EfscBmvService', true],
            'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController:edit' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController:usersList' => ['privates', '.service_locator.Nhkyqt4', 'get_ServiceLocator_Nhkyqt4Service', true],
            'App\\Controller\\FaitController:deleteBudget' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FaitController:editBudget' => ['privates', '.service_locator.Z6kC591', 'get_ServiceLocator_Z6kC591Service', true],
            'App\\Controller\\FaitController:newBudget' => ['privates', '.service_locator.Z6kC591', 'get_ServiceLocator_Z6kC591Service', true],
            'App\\Controller\\FaitController:reporting' => ['privates', '.service_locator.9dX6zbm', 'get_ServiceLocator_9dX6zbmService', true],
            'App\\Controller\\FaitController:saisieBudgetaire' => ['privates', '.service_locator.Ojk124q', 'get_ServiceLocator_Ojk124qService', true],
            'App\\Controller\\MoisController:choixMois' => ['privates', '.service_locator.Bs1IPwp', 'get_ServiceLocator_Bs1IPwpService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.Kn9Vk3z', 'get_ServiceLocator_Kn9Vk3zService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\AdminController::changePassword' => '?',
            'App\\Controller\\AdminController::deleteUser' => '?',
            'App\\Controller\\AdminController::edit' => '?',
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::usersList' => '?',
            'App\\Controller\\FaitController::deleteBudget' => '?',
            'App\\Controller\\FaitController::editBudget' => '?',
            'App\\Controller\\FaitController::newBudget' => '?',
            'App\\Controller\\FaitController::reporting' => '?',
            'App\\Controller\\FaitController::saisieBudgetaire' => '?',
            'App\\Controller\\MoisController::choixMois' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:changePassword' => '?',
            'App\\Controller\\AdminController:deleteUser' => '?',
            'App\\Controller\\AdminController:edit' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:usersList' => '?',
            'App\\Controller\\FaitController:deleteBudget' => '?',
            'App\\Controller\\FaitController:editBudget' => '?',
            'App\\Controller\\FaitController:newBudget' => '?',
            'App\\Controller\\FaitController:reporting' => '?',
            'App\\Controller\\FaitController:saisieBudgetaire' => '?',
            'App\\Controller\\MoisController:choixMois' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
