<?php

namespace ContainerFI2O0Ly;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoisControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MoisController' shared autowired service.
     *
     * @return \App\Controller\MoisController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MoisController'] = $instance = new \App\Controller\MoisController(($container->privates['App\\Repository\\MoisRepository'] ?? $container->load('getMoisRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\MoisController', $container));

        return $instance;
    }
}
