<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgyvKLs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgyvKLs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgyvKLs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgyvKLs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNgyvKLs\App_KernelDevDebugContainer([
    'container.build_hash' => 'NgyvKLs',
    'container.build_id' => 'ca3a3475',
    'container.build_time' => 1649571924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgyvKLs');
