<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsCC6CO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsCC6CO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBsCC6CO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBsCC6CO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBsCC6CO\App_KernelDevDebugContainer([
    'container.build_hash' => 'BsCC6CO',
    'container.build_id' => '592e2bf0',
    'container.build_time' => 1649574445,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBsCC6CO');
