<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFBDLbon\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFBDLbon/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFBDLbon.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFBDLbon\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFBDLbon\App_KernelDevDebugContainer([
    'container.build_hash' => 'FBDLbon',
    'container.build_id' => '3957639e',
    'container.build_time' => 1650297127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFBDLbon');
